// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Options;

/// <summary>
///     <a target="_blank" href="https://docs.geoblazor.com/pages/classes/dymaptic.GeoBlazor.Core.Options.FeatureLayerSaveOptions.html">GeoBlazor Docs</a>
///     
/// </summary>
/// <param name="IgnoreUnsupported">
/// </param>
public partial record FeatureLayerSaveOptions(
    bool? IgnoreUnsupported = null)
{
    /// <summary>
    ///     
    /// </summary>
    public bool? IgnoreUnsupported { get; set; } = IgnoreUnsupported;
    
}
