// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Enums;

/// <summary>
///     <a target="_blank" href="https://docs.geoblazor.com/pages/classes/dymaptic.GeoBlazor.Core.Enums.CoverageInfoVersion.html">GeoBlazor Docs</a>
///     <summary>
///          The service version.
///          <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-WCSLayer.html#CoverageInfo">ArcGIS Maps SDK for JavaScript</a>
///      </summary>
/// </summary>
[JsonConverter(typeof(EnumToKebabCaseStringConverter<CoverageInfoVersion>))]
public enum CoverageInfoVersion
{
#pragma warning disable CS1591
    One_0_0,
    One_1_0,
    One_1_1,
    One_1_2,
    Two_0_1,
    OnePointZeroPointZero,
    OnePointOnePointZero,
    OnePointOnePointOne,
    OnePointOnePointTwo,
    TwoPointZeroPointOne
#pragma warning restore CS1591
}
