// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Enums;

/// <summary>
///     <a target="_blank" href="https://docs.geoblazor.com/pages/classes/dymaptic.GeoBlazor.Core.Enums.PortalUserAccess.html">GeoBlazor Docs</a>
///     Enumeration for PortalUserAccess
/// </summary>
[JsonConverter(typeof(EnumToKebabCaseStringConverter<PortalUserAccess>))]
public enum PortalUserAccess
{
#pragma warning disable CS1591
    Private,
    Org,
    Public
#pragma warning restore CS1591
}
