// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Enums;

/// <summary>
///     Enumeration for SelectionMode
/// </summary>
[JsonConverter(typeof(EnumToKebabCaseStringConverter<SelectionMode>))]
public enum SelectionMode
{
#pragma warning disable CS1591
    Multiple,
    None,
    Single,
    SinglePersist
#pragma warning restore CS1591
}
