// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Enums;

/// <summary>
///     Possible layouts of the <see cref="SliderWidget"/>
/// </summary>
[JsonConverter(typeof(EnumToKebabCaseStringConverter<SliderLayout>))]
public enum SliderLayout
{
#pragma warning disable CS1591
    Horizontal,
    HorizontalReversed,
    Vertical,
    VerticalReversed
#pragma warning restore CS1591
}
