// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Interfaces;

/// <summary>
///     <a target="_blank" href="https://docs.geoblazor.com/pages/classes/dymaptic.GeoBlazor.Core.Interfaces.IFeatureLayerBase.html">GeoBlazor Docs</a>
///     Interface for types CatalogLayer, FeatureLayer
/// </summary>
public partial interface IFeatureLayerBase : IMapComponent
{
#region Properties

    /// <summary>
    ///     Describes the layer's supported capabilities.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#capabilities">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    FeatureLayerCapabilities? Capabilities { get; }
    
    /// <summary>
    ///     Copyright information for the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#copyright">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? Copyright { get; set; }
    
    /// <summary>
    ///     The time zone that dates are stored in.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#dateFieldsTimeZone">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? DateFieldsTimeZone { get; set; }
    
    /// <summary>
    ///     This property is set by the service publisher and indicates that dates should be considered without the local timezone.
    ///     default false
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#datesInUnknownTimezone">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? DatesInUnknownTimezone { get; }
    
    /// <summary>
    ///     The SQL where clause used to filter features on the client.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#definitionExpression">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? DefinitionExpression { get; set; }
    
    /// <summary>
    ///     The name of the layer's primary display field.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#displayField">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? DisplayField { get; set; }
    
    /// <summary>
    ///     The editor tracking fields, which record who adds or edits the data through the feature service and when edits are made.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#editFieldsInfo">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    EditFieldsInfo? EditFieldsInfo { get; }
    
    /// <summary>
    ///     Specifies information about editing.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#editingInfo">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    EditingInfo? EditingInfo { get; }
    
    /// <summary>
    ///     Describes effective capabilities of the layer taking in to consideration privileges of the currently signed-in user.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#effectiveCapabilities">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    Capabilities? EffectiveCapabilities { get; }
    
    /// <summary>
    ///     Indicates whether the layer is editable taking in to consideration privileges of the currently signed-in user.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#effectiveEditingEnabled">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? EffectiveEditingEnabled { get; }
    
    /// <summary>
    ///     Specifies how features are placed on the vertical axis (z).
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#elevationInfo">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    FeatureLayerBaseElevationInfo? ElevationInfo { get; set; }
    
    /// <summary>
    ///     A convenient property that can be used to make case-insensitive lookups for a field by name.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#fieldsIndex">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    FieldsIndex? FieldsIndex { get; }
    
    /// <summary>
    ///     When a feature layer is configured as floor-aware, it has a floorInfo property defined.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#floorInfo">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    LayerFloorInfo? FloorInfo { get; set; }
    
    /// <summary>
    ///     The full extent of the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#fullExtent">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    Extent? FullExtent { get; set; }
    
    /// <summary>
    ///     The version of the geodatabase of the feature service data.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#gdbVersion">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? GdbVersion { get; set; }
    
    /// <summary>
    ///     Provides information on the system maintained area and length fields along with their respective units.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#geometryFieldsInfo">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    GeometryFieldsInfo? GeometryFieldsInfo { get; }
    
    /// <summary>
    ///     The geometry type of features in the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#geometryType">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    FeatureGeometryType? GeometryType { get; }
    
    /// <summary>
    ///     Indicates whether the client-side features in the layer have `M` (measurement) values.
    ///     default undefined
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#hasM">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? HasM { get; set; }
    
    /// <summary>
    ///     Indicates whether the client-side features in the layer have `Z` (elevation) values.
    ///     default undefined
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#hasZ">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? HasZ { get; set; }
    
    /// <summary>
    ///     The historic moment to query.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#historicMoment">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    DateTime? HistoricMoment { get; set; }
    
    /// <summary>
    ///     Returns `true` if the layer is loaded from a non-spatial table in a service.
    ///     default false
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#isTable">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? IsTable { get; }
    
    /// <summary>
    ///     The layer ID, or layer index, of a Feature Service layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#layerId">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    int? LayerIndex { get; set; }
    
    /// <summary>
    ///     The name of an `oid` <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#fields">field</a> containing a unique value or identifier for each feature in the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#objectIdField">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? ObjectIdField { get; set; }
    
    /// <summary>
    ///     The IANA time zone the author of the service intended data from date fields to be viewed in.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#preferredTimeZone">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? PreferredTimeZone { get; }
    
    /// <summary>
    ///     Array of <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-Relationship.html">relationships</a> set up for the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#relationships">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    IReadOnlyList<Relationship>? Relationships { get; }
    
    /// <summary>
    ///     When `true`, indicates that M values will be returned.
    ///     default undefined
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#returnM">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? ReturnM { get; set; }
    
    /// <summary>
    ///     When `true`, indicates that z-values will always be returned.
    ///     default undefined
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#returnZ">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    bool? ReturnZ { get; set; }
    
    /// <summary>
    ///     The service definition expression limits the features available for display and query.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#serviceDefinitionExpression">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? ServiceDefinitionExpression { get; }
    
    /// <summary>
    ///     Indicates the portal item of the hosted feature service that contains this layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#serviceItemId">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? ServiceItemId { get; }
    
    /// <summary>
    ///     The <a target="_blank" href="https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm">feature service's metadata JSON</a> exposed by the ArcGIS REST API.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#sourceJSON">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    object? SourceJSON { get; set; }
    
    /// <summary>
    ///     The spatial reference of the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#spatialReference">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    SpatialReference? SpatialReference { get; set; }
    
    /// <summary>
    ///     The name of the field which holds the id of the <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#subtypes">subtypes</a>.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#subtypeField">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? SubtypeField { get; }
    
    /// <summary>
    ///     An array of <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-Subtype.html">subtypes</a> defined in the layer.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#subtypes">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    IReadOnlyList<Subtype>? Subtypes { get; }
    
    /// <summary>
    ///     The title of the layer used to identify it in places such as the <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html">Legend</a> and <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-LayerList.html">LayerList</a> widgets.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#title">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? Title { get; set; }
    
    /// <summary>
    ///     The absolute URL of the REST endpoint of the layer, non-spatial table or service.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#url">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    string? Url { get; set; }
    
    /// <summary>
    ///     The version of ArcGIS Server in which the layer is published.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#version">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    double? Version { get; }
    
#endregion

#region Property Setters

    /// <summary>
    ///    Asynchronously set the value of the Copyright property after render.
    /// </summary>
    Task SetCopyright(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the DateFieldsTimeZone property after render.
    /// </summary>
    Task SetDateFieldsTimeZone(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the DefinitionExpression property after render.
    /// </summary>
    Task SetDefinitionExpression(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the DisplayField property after render.
    /// </summary>
    Task SetDisplayField(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the ElevationInfo property after render.
    /// </summary>
    Task SetElevationInfo(FeatureLayerBaseElevationInfo? value);
    
    /// <summary>
    ///    Asynchronously set the value of the FloorInfo property after render.
    /// </summary>
    Task SetFloorInfo(LayerFloorInfo? value);
    
    /// <summary>
    ///    Asynchronously set the value of the FullExtent property after render.
    /// </summary>
    Task SetFullExtent(Extent? value);
    
    /// <summary>
    ///    Asynchronously set the value of the GdbVersion property after render.
    /// </summary>
    Task SetGdbVersion(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the HasM property after render.
    /// </summary>
    Task SetHasM(bool? value);
    
    /// <summary>
    ///    Asynchronously set the value of the HasZ property after render.
    /// </summary>
    Task SetHasZ(bool? value);
    
    /// <summary>
    ///    Asynchronously set the value of the HistoricMoment property after render.
    /// </summary>
    Task SetHistoricMoment(DateTime? value);
    
    /// <summary>
    ///    Asynchronously set the value of the LayerIndex property after render.
    /// </summary>
    Task SetLayerIndex(int? value);
    
    /// <summary>
    ///    Asynchronously set the value of the ObjectIdField property after render.
    /// </summary>
    Task SetObjectIdField(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the ReturnM property after render.
    /// </summary>
    Task SetReturnM(bool? value);
    
    /// <summary>
    ///    Asynchronously set the value of the ReturnZ property after render.
    /// </summary>
    Task SetReturnZ(bool? value);
    
    /// <summary>
    ///    Asynchronously set the value of the SourceJSON property after render.
    /// </summary>
    Task SetSourceJSON(object? value);
    
    /// <summary>
    ///    Asynchronously set the value of the SpatialReference property after render.
    /// </summary>
    Task SetSpatialReference(SpatialReference? value);
    
    /// <summary>
    ///    Asynchronously set the value of the Title property after render.
    /// </summary>
    Task SetTitle(string? value);
    
    /// <summary>
    ///    Asynchronously set the value of the Url property after render.
    /// </summary>
    Task SetUrl(string? value);
    
#endregion

#region Property Getters

    /// <summary>
    ///     Asynchronously retrieve the current value of the Capabilities property.
    /// </summary>
    Task<FeatureLayerCapabilities?> GetCapabilities();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Copyright property.
    /// </summary>
    Task<string?> GetCopyright();

    /// <summary>
    ///     Asynchronously retrieve the current value of the DateFieldsTimeZone property.
    /// </summary>
    Task<string?> GetDateFieldsTimeZone();

    /// <summary>
    ///     Asynchronously retrieve the current value of the DatesInUnknownTimezone property.
    /// </summary>
    Task<bool?> GetDatesInUnknownTimezone();

    /// <summary>
    ///     Asynchronously retrieve the current value of the DefinitionExpression property.
    /// </summary>
    Task<string?> GetDefinitionExpression();

    /// <summary>
    ///     Asynchronously retrieve the current value of the DisplayField property.
    /// </summary>
    Task<string?> GetDisplayField();

    /// <summary>
    ///     Asynchronously retrieve the current value of the EditFieldsInfo property.
    /// </summary>
    Task<EditFieldsInfo?> GetEditFieldsInfo();

    /// <summary>
    ///     Asynchronously retrieve the current value of the EditingInfo property.
    /// </summary>
    Task<EditingInfo?> GetEditingInfo();

    /// <summary>
    ///     Asynchronously retrieve the current value of the EffectiveCapabilities property.
    /// </summary>
    Task<Capabilities?> GetEffectiveCapabilities();

    /// <summary>
    ///     Asynchronously retrieve the current value of the EffectiveEditingEnabled property.
    /// </summary>
    Task<bool?> GetEffectiveEditingEnabled();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ElevationInfo property.
    /// </summary>
    Task<FeatureLayerBaseElevationInfo?> GetElevationInfo();

    /// <summary>
    ///     Asynchronously retrieve the current value of the FieldsIndex property.
    /// </summary>
    Task<FieldsIndex?> GetFieldsIndex();

    /// <summary>
    ///     Asynchronously retrieve the current value of the FloorInfo property.
    /// </summary>
    Task<LayerFloorInfo?> GetFloorInfo();

    /// <summary>
    ///     Asynchronously retrieve the current value of the FullExtent property.
    /// </summary>
    Task<Extent?> GetFullExtent();

    /// <summary>
    ///     Asynchronously retrieve the current value of the GdbVersion property.
    /// </summary>
    Task<string?> GetGdbVersion();

    /// <summary>
    ///     Asynchronously retrieve the current value of the GeometryFieldsInfo property.
    /// </summary>
    Task<GeometryFieldsInfo?> GetGeometryFieldsInfo();

    /// <summary>
    ///     Asynchronously retrieve the current value of the GeometryType property.
    /// </summary>
    Task<FeatureGeometryType?> GetGeometryType();

    /// <summary>
    ///     Asynchronously retrieve the current value of the HasM property.
    /// </summary>
    Task<bool?> GetHasM();

    /// <summary>
    ///     Asynchronously retrieve the current value of the HasZ property.
    /// </summary>
    Task<bool?> GetHasZ();

    /// <summary>
    ///     Asynchronously retrieve the current value of the HistoricMoment property.
    /// </summary>
    Task<DateTime?> GetHistoricMoment();

    /// <summary>
    ///     Asynchronously retrieve the current value of the IsTable property.
    /// </summary>
    Task<bool?> GetIsTable();

    /// <summary>
    ///     Asynchronously retrieve the current value of the LayerIndex property.
    /// </summary>
    Task<int?> GetLayerIndex();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ObjectIdField property.
    /// </summary>
    Task<string?> GetObjectIdField();

    /// <summary>
    ///     Asynchronously retrieve the current value of the PreferredTimeZone property.
    /// </summary>
    Task<string?> GetPreferredTimeZone();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Relationships property.
    /// </summary>
    Task<IReadOnlyList<Relationship>?> GetRelationships();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ReturnM property.
    /// </summary>
    Task<bool?> GetReturnM();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ReturnZ property.
    /// </summary>
    Task<bool?> GetReturnZ();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ServiceDefinitionExpression property.
    /// </summary>
    Task<string?> GetServiceDefinitionExpression();

    /// <summary>
    ///     Asynchronously retrieve the current value of the ServiceItemId property.
    /// </summary>
    Task<string?> GetServiceItemId();

    /// <summary>
    ///     Asynchronously retrieve the current value of the SourceJSON property.
    /// </summary>
    Task<object?> GetSourceJSON();

    /// <summary>
    ///     Asynchronously retrieve the current value of the SpatialReference property.
    /// </summary>
    Task<SpatialReference?> GetSpatialReference();

    /// <summary>
    ///     Asynchronously retrieve the current value of the SubtypeField property.
    /// </summary>
    Task<string?> GetSubtypeField();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Subtypes property.
    /// </summary>
    Task<IReadOnlyList<Subtype>?> GetSubtypes();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Title property.
    /// </summary>
    Task<string?> GetTitle();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Url property.
    /// </summary>
    Task<string?> GetUrl();

    /// <summary>
    ///     Asynchronously retrieve the current value of the Version property.
    /// </summary>
    Task<double?> GetVersion();

#endregion

#region Public Methods

    /// <summary>
    ///     Query information about attachments associated with features.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#queryAttachments">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    /// <param name="attachmentQuery">
    /// </param>
    /// <param name="cancellationToken">
    ///     The CancellationToken to cancel an asynchronous operation.
    /// </param>
    [ArcGISMethod]
    Task<AttachmentsQueryResult?> QueryAttachments(AttachmentQuery attachmentQuery,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    ///     Saves the layer to its existing portal item in the <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-Portal.html">Portal</a> authenticated within the user's current session.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#save">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    /// <param name="options">
    /// </param>
    [ArcGISMethod]
    Task<PortalItem?> Save(FeatureLayerBaseSaveOptions options);
    
    /// <summary>
    ///     Saves the layer to a new portal item in the <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-Portal.html">Portal</a> authenticated within the user's current session.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#saveAs">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    /// <param name="portalItem">
    /// </param>
    /// <param name="options">
    /// </param>
    [ArcGISMethod]
    Task<PortalItem?> SaveAs(PortalItem portalItem,
        FeatureLayerBaseSaveAsOptions options);
    
    /// <summary>
    ///     Updates an existing attachment for a feature.
    ///     <a target="_blank" href="https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-mixins-FeatureLayerBase.html#updateAttachment">ArcGIS Maps SDK for JavaScript</a>
    /// </summary>
    /// <param name="feature">
    /// </param>
    /// <param name="attachmentId">
    /// </param>
    /// <param name="attachment">
    /// </param>
    [ArcGISMethod]
    Task<FeatureEditResult?> UpdateAttachment(Graphic feature,
        long attachmentId,
        ElementReference attachment);
    
#endregion

}
