// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue, lookupGeoBlazorId } from './arcGisJsInterop';
import { buildDotNetCategory } from './category';

export async function buildJsCategoryGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsCategory: any = {};

    if (hasValue(dotNetObject.categoryId)) {
        jsCategory.categoryId = dotNetObject.categoryId;
    }
    if (hasValue(dotNetObject.label)) {
        jsCategory.label = dotNetObject.label;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsCategory);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsCategory;
    
    let { buildDotNetCategory } = await import('./category');
    let dnInstantiatedObject = await buildDotNetCategory(jsCategory);

    try {
        let seenObjects = new WeakMap();
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', 
            jsObjectRef, JSON.stringify(dnInstantiatedObject, function (key, value) {
                if (key.startsWith('_') || key === 'jsComponentReference') {
                    return undefined;
                }
                if (typeof value === 'object' && value !== null
                    && !(Array.isArray(value) && value.length === 0)) {
                    if (seenObjects.has(value)) {
                        console.warn(`Circular reference in serializing type Category detected at path: ${key}, value: ${value.declaredClass}`);
                        return undefined;
                    }
                    seenObjects.set(value, true);
                }
                return value;
            }));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for Category', e);
    }
    
    return jsCategory;
}


export async function buildDotNetCategoryGenerated(jsObject: any): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetCategory: any = {
        jsComponentReference: DotNet.createJSObjectReference(jsObject)
    };
    if (hasValue(jsObject.categoryId)) {
        dotNetCategory.categoryId = jsObject.categoryId;
    }
    if (hasValue(jsObject.label)) {
        dotNetCategory.label = jsObject.label;
    }

    let geoBlazorId = lookupGeoBlazorId(jsObject);
    if (hasValue(geoBlazorId)) {
        dotNetCategory.id = geoBlazorId;
    }

    return dotNetCategory;
}

