// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue } from './arcGisJsInterop';
import { buildDotNetCSVLayerGetFieldDomainOptions } from './cSVLayerGetFieldDomainOptions';

export async function buildJsCSVLayerGetFieldDomainOptionsGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsCSVLayerGetFieldDomainOptions: any = {};

    if (hasValue(dotNetObject.feature)) {
        const { id, dotNetComponentReference, ...sanitizedFeature } = dotNetObject.feature;
        jsCSVLayerGetFieldDomainOptions.feature = sanitizedFeature;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsCSVLayerGetFieldDomainOptions);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsCSVLayerGetFieldDomainOptions;
    
    let { buildDotNetCSVLayerGetFieldDomainOptions } = await import('./cSVLayerGetFieldDomainOptions');
    let dnInstantiatedObject = await buildDotNetCSVLayerGetFieldDomainOptions(jsCSVLayerGetFieldDomainOptions, layerId, viewId);

    try {
        let seenObjects = new WeakMap();
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', 
            jsObjectRef, JSON.stringify(dnInstantiatedObject, function (key, value) {
                if (typeof value === 'object' && value !== null) {
                    if (seenObjects.has(value)) {
                        console.warn(`Circular reference in serializing type CSVLayerGetFieldDomainOptions detected at path: ${key}, value: ${value}`);
                        return undefined;
                    }
                    seenObjects.set(value, true);
                }
                if (key.startsWith('_')) {
                    return undefined;
                }
                return value;
            }));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for CSVLayerGetFieldDomainOptions', e);
    }
    
    return jsCSVLayerGetFieldDomainOptions;
}


export async function buildDotNetCSVLayerGetFieldDomainOptionsGenerated(jsObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetCSVLayerGetFieldDomainOptions: any = {
        jsComponentReference: DotNet.createJSObjectReference(jsObject)
    };
    if (hasValue(jsObject.feature)) {
        dotNetCSVLayerGetFieldDomainOptions.feature = jsObject.feature;
    }

    if (Object.values(arcGisObjectRefs).includes(jsObject)) {
        for (const k of Object.keys(arcGisObjectRefs)) {
            if (arcGisObjectRefs[k] === jsObject) {
                dotNetCSVLayerGetFieldDomainOptions.id = k;
                break;
            }
        }
    }

    return dotNetCSVLayerGetFieldDomainOptions;
}

