// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import GeotriggersInfo from '@arcgis/core/webdoc/GeotriggersInfo';
import { arcGisObjectRefs, jsObjectRefs, hasValue, removeCircularReferences } from './geoBlazorCore';

export async function buildJsGeotriggersInfoGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    if (!hasValue(dotNetObject)) {
        return null;
    }

    let properties: any = {};

    if (hasValue(dotNetObject.geotriggers) && dotNetObject.geotriggers.length > 0) {
        properties.geotriggers = dotNetObject.geotriggers;
    }
    let jsGeotriggersInfo = new GeotriggersInfo(properties);
    
    jsObjectRefs[dotNetObject.id] = jsGeotriggersInfo;
    arcGisObjectRefs[dotNetObject.id] = jsGeotriggersInfo;
    
    return jsGeotriggersInfo;
}


export async function buildDotNetGeotriggersInfoGenerated(jsObject: any, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetGeotriggersInfo: any = {};
    
    if (hasValue(jsObject.geotriggers)) {
        dotNetGeotriggersInfo.geotriggers = removeCircularReferences(jsObject.geotriggers);
    }
    

    return dotNetGeotriggersInfo;
}

