// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue } from './arcGisJsInterop';
import { buildDotNetHeatmapSliderViewModelStopInfo } from './heatmapSliderViewModelStopInfo';

export async function buildJsHeatmapSliderViewModelStopInfoGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsHeatmapSliderViewModelStopInfo: any = {};
    if (hasValue(dotNetObject.color)) {
        let { buildJsMapColor } = await import('./mapColor');
        jsHeatmapSliderViewModelStopInfo.color = buildJsMapColor(dotNetObject.color) as any;
    }

    if (hasValue(dotNetObject.offset)) {
        jsHeatmapSliderViewModelStopInfo.offset = dotNetObject.offset;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsHeatmapSliderViewModelStopInfo);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsHeatmapSliderViewModelStopInfo;
    
    let dnInstantiatedObject = await buildDotNetHeatmapSliderViewModelStopInfo(jsHeatmapSliderViewModelStopInfo);
    
    try {
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', jsObjectRef, JSON.stringify(dnInstantiatedObject));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for HeatmapSliderViewModelStopInfo', e);
    }
    
    return jsHeatmapSliderViewModelStopInfo;
}

export async function buildDotNetHeatmapSliderViewModelStopInfoGenerated(jsObject: any): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetHeatmapSliderViewModelStopInfo: any = {
        // @ts-ignore
        jsComponentReference: DotNet.createJSObjectReference(jsObject)
    };
        if (hasValue(jsObject.color)) {
            let { buildDotNetMapColor } = await import('./mapColor');
            dotNetHeatmapSliderViewModelStopInfo.color = buildDotNetMapColor(jsObject.color);
        }
    if (hasValue(jsObject.offset)) {
        dotNetHeatmapSliderViewModelStopInfo.offset = jsObject.offset;
    }

    if (Object.values(arcGisObjectRefs).includes(jsObject)) {
        for (const k of Object.keys(arcGisObjectRefs)) {
            if (arcGisObjectRefs[k] === jsObject) {
                dotNetHeatmapSliderViewModelStopInfo.id = k;
                break;
            }
        }
    }

    return dotNetHeatmapSliderViewModelStopInfo;
}

