// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import ChartMediaInfo from '@arcgis/core/popup/content/mixins/ChartMediaInfo';
import { sanitize } from './arcGisJsInterop';
export function buildJsIChartMediaInfoGenerated(dotNetObject: any): any {
    return sanitize(dotNetObject);
}

export function buildDotNetIChartMediaInfoGenerated(jsObject: any): any {
    return jsObject;
}

