// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { sanitize } from './arcGisJsInterop';
export function buildJsIOperationalLayerGenerated(dotNetObject: any): any {
    return sanitize(dotNetObject);
}

export function buildDotNetIOperationalLayerGenerated(jsObject: any): any {
    return jsObject;
}

