// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue, lookupGeoBlazorId, sanitize } from './arcGisJsInterop';
import { buildDotNetISceneService } from './iSceneService';

export async function buildJsISceneServiceGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsSceneService: any = {};

    if (hasValue(dotNetObject.copyright)) {
        jsSceneService.copyright = dotNetObject.copyright;
    }
    if (hasValue(dotNetObject.sceneServiceLayerId)) {
        jsSceneService.layerId = dotNetObject.sceneServiceLayerId;
    }
    if (hasValue(dotNetObject.spatialReference)) {
        jsSceneService.spatialReference = sanitize(dotNetObject.spatialReference);
    }
    if (hasValue(dotNetObject.url)) {
        jsSceneService.url = dotNetObject.url;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsSceneService);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsSceneService;
    
    let { buildDotNetISceneService } = await import('./iSceneService');
    let dnInstantiatedObject = await buildDotNetISceneService(jsSceneService, layerId, viewId);

    try {
        let seenObjects = new WeakMap();
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', 
            jsObjectRef, JSON.stringify(dnInstantiatedObject, function (key, value) {
                if (key.startsWith('_') || key === 'jsComponentReference') {
                    return undefined;
                }
                if (typeof value === 'object' && value !== null
                    && !(Array.isArray(value) && value.length === 0)) {
                    if (seenObjects.has(value)) {
                        console.debug(`Circular reference in serializing type ISceneService detected at path: ${key}, value: ${value.declaredClass}`);
                        return undefined;
                    }
                    seenObjects.set(value, true);
                }
                return value;
            }));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for ISceneService', e);
    }
    
    return jsSceneService;
}


export async function buildDotNetISceneServiceGenerated(jsObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let geoBlazorId = lookupGeoBlazorId(jsObject);
    
    let jsComponentRef: any;
    if (hasValue(geoBlazorId)) {
        jsComponentRef = jsObjectRefs[geoBlazorId!];
    } else {
        let { buildJsISceneService } = await import('./iSceneService');
        jsComponentRef = await buildJsISceneService(jsObject, layerId, viewId);
    }
    
    let dotNetISceneService: any = {
        jsComponentReference: DotNet.createJSObjectReference(jsComponentRef)
    };
    if (hasValue(jsObject.copyright)) {
        dotNetISceneService.copyright = jsObject.copyright;
    }
    if (hasValue(jsObject.layerId)) {
        dotNetISceneService.sceneServiceLayerId = jsObject.layerId;
    }
    if (hasValue(jsObject.spatialReference)) {
        dotNetISceneService.spatialReference = jsObject.spatialReference;
    }
    if (hasValue(jsObject.url)) {
        dotNetISceneService.url = jsObject.url;
    }
    if (hasValue(jsObject.version)) {
        dotNetISceneService.version = jsObject.version;
    }


    if (hasValue(geoBlazorId)) {
        dotNetISceneService.id = geoBlazorId;
    }

    return dotNetISceneService;
}

