// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue, lookupGeoBlazorId } from './arcGisJsInterop';
import { buildDotNetLayerInclusionDefinition } from './layerInclusionDefinition';

export async function buildJsLayerInclusionDefinitionGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsLayerInclusionDefinition: any = {};
    if (hasValue(dotNetObject.members)) {
        let { buildJsLayerInclusionMemberDefinition } = await import('./layerInclusionMemberDefinition');
        jsLayerInclusionDefinition.members = await buildJsLayerInclusionMemberDefinition(dotNetObject.members, layerId, viewId) as any;
    }

    if (hasValue(dotNetObject.useAllData)) {
        jsLayerInclusionDefinition.useAllData = dotNetObject.useAllData;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsLayerInclusionDefinition);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsLayerInclusionDefinition;
    
    let { buildDotNetLayerInclusionDefinition } = await import('./layerInclusionDefinition');
    let dnInstantiatedObject = await buildDotNetLayerInclusionDefinition(jsLayerInclusionDefinition);

    try {
        let seenObjects = new WeakMap();
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', 
            jsObjectRef, JSON.stringify(dnInstantiatedObject, function (key, value) {
                if (key.startsWith('_') || key === 'jsComponentReference') {
                    return undefined;
                }
                if (typeof value === 'object' && value !== null
                    && !(Array.isArray(value) && value.length === 0)) {
                    if (seenObjects.has(value)) {
                        console.debug(`Circular reference in serializing type LayerInclusionDefinition detected at path: ${key}, value: ${value.declaredClass}`);
                        return undefined;
                    }
                    seenObjects.set(value, true);
                }
                return value;
            }));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for LayerInclusionDefinition', e);
    }
    
    return jsLayerInclusionDefinition;
}


export async function buildDotNetLayerInclusionDefinitionGenerated(jsObject: any): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetLayerInclusionDefinition: any = {
        jsComponentReference: DotNet.createJSObjectReference(jsObject)
    };
    if (hasValue(jsObject.members)) {
        let { buildDotNetLayerInclusionMemberDefinition } = await import('./layerInclusionMemberDefinition');
        dotNetLayerInclusionDefinition.members = await buildDotNetLayerInclusionMemberDefinition(jsObject.members);
    }
    if (hasValue(jsObject.useAllData)) {
        dotNetLayerInclusionDefinition.useAllData = jsObject.useAllData;
    }

    let geoBlazorId = lookupGeoBlazorId(jsObject);
    if (hasValue(geoBlazorId)) {
        dotNetLayerInclusionDefinition.id = geoBlazorId;
    }

    return dotNetLayerInclusionDefinition;
}

