// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { hasValue, removeCircularReferences } from './arcGisJsInterop';

export async function buildDotNetLegendLayerInfosGenerated(jsObject: any, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetLegendLayerInfos: any = {};
    
    if (hasValue(jsObject.layer)) {
        dotNetLegendLayerInfos.layer = removeCircularReferences(jsObject.layer);
    }
    
    if (hasValue(jsObject.sublayerIds)) {
        dotNetLegendLayerInfos.sublayerIds = jsObject.sublayerIds;
    }
    
    if (hasValue(jsObject.title)) {
        dotNetLegendLayerInfos.title = jsObject.title;
    }
    

    return dotNetLegendLayerInfos;
}

