// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file


import RasterDataSource = __esri.RasterDataSource;
import {arcGisObjectRefs, hasValue, jsObjectRefs} from './arcGisJsInterop';
import {IPropertyWrapper} from './definitions';

export default class RasterDataSourceGenerated implements IPropertyWrapper {
    public component: RasterDataSource;
    public geoBlazorId: string | null = null;
    public viewId: string | null = null;
    public layerId: string | null = null;

    constructor(component: RasterDataSource) {
        this.component = component;
    }
    
    // region methods
   
    unwrap() {
        return this.component;
    }
    
    // region properties
    
    getProperty(prop: string): any {
        return this.component[prop];
    }
    
    setProperty(prop: string, value: any): void {
        this.component[prop] = value;
    }
}

export async function buildJsRasterDataSourceGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsRasterDataSource: any = {}

    if (hasValue(dotNetObject.dataSourceName)) {
        jsRasterDataSource.dataSourceName = dotNetObject.dataSourceName;
    }
    if (hasValue(dotNetObject.workspaceId)) {
        jsRasterDataSource.workspaceId = dotNetObject.workspaceId;
    }
    let { default: RasterDataSourceWrapper } = await import('./rasterDataSource');
    let rasterDataSourceWrapper = new RasterDataSourceWrapper(jsRasterDataSource);
    rasterDataSourceWrapper.geoBlazorId = dotNetObject.id;
    rasterDataSourceWrapper.viewId = viewId;
    rasterDataSourceWrapper.layerId = layerId;
    
    // @ts-ignore
    let jsObjectRef = DotNet.createJSObjectReference(rasterDataSourceWrapper);
    jsObjectRefs[dotNetObject.id] = rasterDataSourceWrapper;
    arcGisObjectRefs[dotNetObject.id] = jsRasterDataSource;
    
    try {
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', jsObjectRef);
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for RasterDataSource', e);
    }
    
    return jsRasterDataSource;
}

export async function buildDotNetRasterDataSourceGenerated(jsObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetRasterDataSource: any = {
        // @ts-ignore
        jsComponentReference: DotNet.createJSObjectReference(jsObject)
    };
        if (hasValue(jsObject.dataSourceName)) {
            dotNetRasterDataSource.dataSourceName = jsObject.dataSourceName;
        }
        if (hasValue(jsObject.type)) {
            dotNetRasterDataSource.type = jsObject.type;
        }
        if (hasValue(jsObject.workspaceId)) {
            dotNetRasterDataSource.workspaceId = jsObject.workspaceId;
        }

    if (Object.values(arcGisObjectRefs).includes(jsObject)) {
        for (const k of Object.keys(arcGisObjectRefs)) {
            if (arcGisObjectRefs[k] === jsObject) {
                dotNetRasterDataSource.id = k;
                break;
            }
        }
    }

    return dotNetRasterDataSource;
}

