// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue, lookupGeoBlazorId, removeCircularReferences } from './arcGisJsInterop';
import { buildDotNetSceneLayerElevationInfo } from './sceneLayerElevationInfo';

export async function buildJsSceneLayerElevationInfoGenerated(dotNetObject: any): Promise<any> {
    if (!hasValue(dotNetObject)) {
        return null;
    }

    let jsSceneLayerElevationInfo: any = {};

    if (hasValue(dotNetObject.mode)) {
        jsSceneLayerElevationInfo.mode = dotNetObject.mode;
    }
    if (hasValue(dotNetObject.offset)) {
        jsSceneLayerElevationInfo.offset = dotNetObject.offset;
    }
    if (hasValue(dotNetObject.unit)) {
        jsSceneLayerElevationInfo.unit = dotNetObject.unit;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsSceneLayerElevationInfo);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsSceneLayerElevationInfo;
    
    return jsSceneLayerElevationInfo;
}


export async function buildDotNetSceneLayerElevationInfoGenerated(jsObject: any): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let dotNetSceneLayerElevationInfo: any = {};
    
    if (hasValue(jsObject.mode)) {
        dotNetSceneLayerElevationInfo.mode = removeCircularReferences(jsObject.mode);
    }
    
    if (hasValue(jsObject.offset)) {
        dotNetSceneLayerElevationInfo.offset = jsObject.offset;
    }
    
    if (hasValue(jsObject.unit)) {
        dotNetSceneLayerElevationInfo.unit = removeCircularReferences(jsObject.unit);
    }
    

    let geoBlazorId = lookupGeoBlazorId(jsObject);
    if (hasValue(geoBlazorId)) {
        dotNetSceneLayerElevationInfo.id = geoBlazorId;
    }

    return dotNetSceneLayerElevationInfo;
}

