// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .ts file.
import { arcGisObjectRefs, jsObjectRefs, hasValue, lookupGeoBlazorId } from './arcGisJsInterop';
import { buildDotNetWFSLayerElevationInfo } from './wFSLayerElevationInfo';

export async function buildJsWFSLayerElevationInfoGenerated(dotNetObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    let jsWFSLayerElevationInfo: any = {};
    if (hasValue(dotNetObject.featureExpressionInfo)) {
        let { buildJsWFSLayerElevationInfoFeatureExpressionInfo } = await import('./wFSLayerElevationInfoFeatureExpressionInfo');
        jsWFSLayerElevationInfo.featureExpressionInfo = await buildJsWFSLayerElevationInfoFeatureExpressionInfo(dotNetObject.featureExpressionInfo, layerId, viewId) as any;
    }

    if (hasValue(dotNetObject.mode)) {
        jsWFSLayerElevationInfo.mode = dotNetObject.mode;
    }
    if (hasValue(dotNetObject.offset)) {
        jsWFSLayerElevationInfo.offset = dotNetObject.offset;
    }
    if (hasValue(dotNetObject.unit)) {
        jsWFSLayerElevationInfo.unit = dotNetObject.unit;
    }
    
    let jsObjectRef = DotNet.createJSObjectReference(jsWFSLayerElevationInfo);
    jsObjectRefs[dotNetObject.id] = jsObjectRef;
    arcGisObjectRefs[dotNetObject.id] = jsWFSLayerElevationInfo;
    
    let { buildDotNetWFSLayerElevationInfo } = await import('./wFSLayerElevationInfo');
    let dnInstantiatedObject = await buildDotNetWFSLayerElevationInfo(jsWFSLayerElevationInfo, layerId, viewId);

    try {
        let seenObjects = new WeakMap();
        await dotNetObject.dotNetComponentReference.invokeMethodAsync('OnJsComponentCreated', 
            jsObjectRef, JSON.stringify(dnInstantiatedObject, function (key, value) {
                if (key.startsWith('_') || key === 'jsComponentReference') {
                    return undefined;
                }
                if (typeof value === 'object' && value !== null
                    && !(Array.isArray(value) && value.length === 0)) {
                    if (seenObjects.has(value)) {
                        console.debug(`Circular reference in serializing type WFSLayerElevationInfo detected at path: ${key}, value: ${value.declaredClass}`);
                        return undefined;
                    }
                    seenObjects.set(value, true);
                }
                return value;
            }));
    } catch (e) {
        console.error('Error invoking OnJsComponentCreated for WFSLayerElevationInfo', e);
    }
    
    return jsWFSLayerElevationInfo;
}


export async function buildDotNetWFSLayerElevationInfoGenerated(jsObject: any, layerId: string | null, viewId: string | null): Promise<any> {
    if (!hasValue(jsObject)) {
        return null;
    }
    
    let geoBlazorId = lookupGeoBlazorId(jsObject);
    
    let jsComponentRef: any;
    if (hasValue(geoBlazorId)) {
        jsComponentRef = jsObjectRefs[geoBlazorId!];
    } else {
        let { buildJsWFSLayerElevationInfo } = await import('./wFSLayerElevationInfo');
        jsComponentRef = await buildJsWFSLayerElevationInfo(jsObject, layerId, viewId);
    }
    
    let dotNetWFSLayerElevationInfo: any = {
        jsComponentReference: DotNet.createJSObjectReference(jsComponentRef)
    };
    if (hasValue(jsObject.featureExpressionInfo)) {
        let { buildDotNetWFSLayerElevationInfoFeatureExpressionInfo } = await import('./wFSLayerElevationInfoFeatureExpressionInfo');
        dotNetWFSLayerElevationInfo.featureExpressionInfo = await buildDotNetWFSLayerElevationInfoFeatureExpressionInfo(jsObject.featureExpressionInfo, layerId, viewId);
    }
    if (hasValue(jsObject.mode)) {
        dotNetWFSLayerElevationInfo.mode = jsObject.mode;
    }
    if (hasValue(jsObject.offset)) {
        dotNetWFSLayerElevationInfo.offset = jsObject.offset;
    }
    if (hasValue(jsObject.unit)) {
        dotNetWFSLayerElevationInfo.unit = jsObject.unit;
    }


    if (hasValue(geoBlazorId)) {
        dotNetWFSLayerElevationInfo.id = geoBlazorId;
    }

    return dotNetWFSLayerElevationInfo;
}

