// File auto-generated by dymaptic tooling. Any changes made here will be lost on future generation. To override functionality, use the relevant root .cs file.

namespace dymaptic.GeoBlazor.Core.Events;

/// <summary>
///     <a target="_blank" href="https://docs.geoblazor.com/pages/classes/dymaptic.GeoBlazor.Core.Events.LocateEvent.html">GeoBlazor Docs</a>
///     Event result type for the LocateWidget.OnLocate event.
/// </summary>
/// <param name="Position">
/// </param>
public partial record LocateEvent(
    [property:JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    object? Position = null);
